language: java
before_install:
- sudo apt-get update
- sudo apt-get install sshpass
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: KeRgFs8hj9cXdvcspH2104MIoUMQlIBznwZ9An1UBPBCRuVPylhPW3qps132XV6ap4CztVWH9x3Wn4k4qx+uE+hk8/wFXlGkgU5LLyGzEabnVKqr7XiEra7m0Zuyhz9gHINJgm7DDrVKRNR+nnU8iF8dz5hAj9tPzf41cdqnVBFE8WS6LNUIy5o3zKJx4CdMYhRDgplntQe1wo1iTrzmr7zGBXRQRyiaQGQ1Sk2DNNxXVyEp1wfV5LxVt6Qims0CWSgSfa7UT/zTiLBXjcj3owUVdLg5YwYHtlt65U/0Z2GBbNl5xC59RQ1i9E1+Gh86KQy5Q5DJjaE6gVt4B7Cn6/NM8+E/YKSGcFAJrMFm89/deUk5fzdB+NQ7kSo/isxaU1XsVuIEheunQzwtg/CjHr8+gRZbMqZTOkCrxgSY3B8iTMRiQpDaxXXbTgiwTO4Ky5TcxIbveNjPZQICiGfS7rKifd09IfiKG3BuuRLr7zadarFc4HoeIHobt9nALCEeXoGianIh6g7FBCdqJelvM+t7a7GDD4BgnvvAoBCiMNXkbbZvKCwY9J9TgFafTOM+cIgVxRRmp1p7NMGDz5WzqPOhZrhTWOpIbRImail3K6PEyf8sWrCyEjwr4IlRPu+rBgN12niZvXI109Xp3PWXEZkpJw9n0gaEkj+jyyk08IE=
after_success: sshpass -p $COPY_CMD
