language: java
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: W9BcyKu3GvTuS5/J7V4boEwwf8/NXLfA4IpoHryakbBXkabsd5PN26LVFw2cgUe8bXLSdBoEsxP54pvTsM3WP2fDccT+cg23xjkYHutcFb1NEFCLCWZQn9yp2CQoU80fX6iash8aLL7nTgHBwQQaVl27e5l9mfiTkqrumNefSiDu10UtbHsW//17junjgvIIG15xwMJSoeOFrWjLAw7ZtzQUpEvddviitroezDfVOZoZZ6IvBMxp+6raxE+ZALSFoohaHQmYUj6p+d9/+EATT7w+9vxMUq7uMzoXFeu3vZtVmGKxrHxv5PL64fFgszmbiXJTA74GBkLY2n9RNjh9cVZp9cq8fdq1i+QDpuPk8Bc4eJ7PDDWMWBYE3ERIgmjKJwa0jlVF56vvvSaiw5PU0yid2w6EIbYoyjrdGeUgF4cXnv/smDQbM24Oo+ddZi0llxZj2HV/dy302SLjlWc4vk3ve9U1NHkgySRDJatBIFtBuFcs6knqq50rJNixONdqNiL3cYfbV8R7Q4UxdYThE5zJFcH5lN/SzCjZVFjDFs2hKN93ISjNa26PFZvcwTWglnRN6Q+oMSwTWk8r42FVRbovEn5p5+ZePoCo1j2QAIbdQ+3lHaOYARIC+bqH8eVgj7oJsTL2OB9F/rlYKqAbAQmOtykwZZxJXkJtld+357I=
after_success: scp [-P 22] target/lab-bot-0.0.1-SNAPSHOT.jar $ALL_IP
