language: java
before_install:
- sudo apt-get update
- sudo apt-get install sshpass
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: QJn8Tnnixt+w2dDYfTbB7QyR5Soo8j/jWClZSj2ZPEnc52II+xIiXBRoNwGkzt4oAhTwucg8Qg53/hJ1dt8zhLxQ6psJNkW/H3jw8HeRTww2UYOLS8GlpRe63k+LJUS4eGpqkcHIhQe0JatvMM4fNA3h81Zk8jzIMWUs0aq13AiPWOg7y8jd6VbJaojKXg4an5SRu2j0Q52XmwIQUQz1j6sYOPpbBPpHElLek4wx62xA2Tkh+fFNN+m+wXU9idcSJ941075nKCd6gj0cNFWLNMAFAE8XofTThKieU0Hzl9rHbdmy9hVR2gIHVq/FJyvGi7ZrmA+Qs1oZbnl/SuYFgI8CZKM9P0sBEwpO+MXp7okJNSUHDiRd6VCpeW5IVn8cYXoPPGynKLumBRQDj/r1ptu6sVP7KWSefMN0E2nkJV/72GBhar6He0p2YydYSH7+9jmG+CbUFTP5NP8c3jeU/eJp3ORuXp+2fEuz3jHonLE+AFYmaxB+9z7l+GkgMWcTEYZXlGWT/fV5eaxntY5QvqWg5YduE5trQeaJmMBkv1zSI80RkdCwYIfdkFcoqzycB7lp/wZsrWp16qIF3SRTpiN6tDfLgvgNaYwQV32ByMXTJTEImFurA2zNdeUj/LR207eN+vEpZrtHxqwBT7KdnUErAfy4robrUQ32auel5Ys=
after_success: "$COPY_CMD"
