language: java
before_install:
- sudo apt-get update
- sudo apt-get install sshpass
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  global:
  - secure: LVN1TnELveCJXBGjIOicLoyt+3lpR+PZhPwPePI9U0FTSFaBRgJSxC+pxFNLfXWmKjQVZuAz5eYH62CPpu9q3DuZYvsOXkq4w5G47jGosVfk0a6lQqS5Y8c3M0IziQT46W3lX2vcNG6sLRE2m+eTkHDmct1NxUhaivA2SEBJg8IgIM4/P+YZBdg3o7bLQZbbzhe3ALOZR0ywyqvld6KJTQSAsnEkABMiGFhuSuCfBnmp049lChDyisnH/KZq15qw6Xc50wcFtW/03I9jbihTHJMTrhTFls7wdt4qrxNIOuVuwBeEqaexPoSJN75WuDfOtIvUbRZJHZq9bNPt9MDryhFyFM/+ZtdGPA09dsxz0MRCtJPrlUMt4YR5FbSDnSmeZ4g/FzuoBhPsyRqYDzlV1YfoO4tB9tVNigkzpmsv1RGaUH/Gj+PPwKBesRGI3XWZt+R8S0blWd0sq5R5XV6Q7frY9DfjobJG8A3lTRYnEjxxKLgzRzRbYHQs93gyGMixaptn6Ql8FrZIz1h+mk29qd6IjWW7sXhWpDRLmVjD9Of8yLVv5uXhYmOc/+yzfykU0gUJZCjhCw9qf80BJsFKAoqgLtkaUzh1U2u0e3kdoAAD3LTr/OCXLfyS9s87Ru/ODcdiu4YkqF9S+twAjYWtC3wf+glk4Dv7TUkwA5Vwz5g=
  - secure: DgPEghlzpG1RO7PlYO43VyM2mCRR/aXhAOi4G/NJjKESIBo1WoinUFE2O1IvVpuJoFmhMIhHf2wKQRJ6b8b4Sz4NX1IDuFhbQ5aZZ4XT7ng68nQGkfXSy1L5NuIWXBxs/4cUf4jFBHnWDFp7HJvW8McBlBoYT3PBZIeADwc5oinPpH7pnoRNWYSuNzr2amvzScK7QwyP9JOZ2kvpJTc5oMRmaQNWyh00JbOoBw7GzV9woVcRJNxx4N/n95zPQ8KIV8V1yXXsp0CeLhJ9xWM3uVA1D66C9bAf1L6L3HukPly4Qx90Q9sUYaOK5z8R6LnW1NxItj9DPcYklwY6uv+lQvvdisDn+USyKltX2QvKweZVp9HDFw0E8CRXFuJp5khRgj/ETdw7dcu7sR7aEs2mre9Ug/7cz500E0TnfvrD1p/ln5qILLj5Jj0nGxNSkDaq74ov+49LsDcXv88f+Cp/GAH9OjkuPT0jG8/ulPcoC72/nR1GnA4EsPsdhN9f8sytmnQ5qU9oNgPY6AllQ/O3T+WFQuz2jHnySniMk2kRF2taatO691x2tjj37sntBxsjQub6Ar2xgejUalvsA8YX8maIo8JJ2rF4cYyPIgMuh1J4rq56x5E9oeMLEW2Wasa+vp74k4Qvs66oVdVeSIe9aS7K5H8xhoOx4r7laQIhVSE=
after_success:
- ls -l
- sshpass -p "$password" scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  target/lab-bot-0.0.1-SNAPSHOT.jar felix@$IP:/home/
- ls target
