language: java
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- apt-get --assume-yes install sshpass
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: gKocQoHJO1vyD02813ITtOzW0H4ZOzCO+PObCHamcM83h8ClM1D+1KpQDrpkWsxq1lQ2t7D5I5H1z7QhuCzmfVcF+vLIFO4qJFeLWZhheHvci6lcH5nuUw9Z3TMt8U2DNnt1k2pOhaAfw26p9KrsK+PXnL5rRObGFesJR0p3jDzLcqQtJeKduCVtNk8Mz1KNnGmEwoJcRXshfFRtDS4NsxbzXldPwzEnHXa5UNzTdwTA3B/rqLkbrUY1xjg9d0cNChtjqFs8V7a3S33NZWAnJau1gjhrcTkhJhVxwIOBL5O2TfEEMabE69H21VsrC94th6nPLq3eRR89/aHVOPGl9QJsNegiIk49o2UJG+JrT7q4D/AQ2Lryy+GZ27B7i1Gfn4VGWk6WEfvR1tsG4GSHgM20Fi1/73LepJIkAncABnvXGFBV3C0zilvvb/AtNEJ8h5mWSpbnYWWMeOO0tIbYcvqmzyk7WikAa2zr454SrRipCTubqcTvwes7dxgUKBzzcIrFCkdvoZRqGV8WkDOIFzDcNu/5hkbDB4EEs4MKXQcgZ9ZkKnyN6jCKHkkGNR8X9pyVuCfmy7jp/CPQJ4kG8pdBkK7/dtPKcqXpEnlc7AYJbozBB7vQZmKC5AXf4w9mKsY0LZyczj0NZRg4h7eMJvRXLi6aR3JmRlybPrIvcwY=
after_success: $COPY_CMD
