language: java
before_install:
- sudo apt-get update
- sudo apt-get install sshpass
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: rejgVLr/mKbykkM6lRASGv4OxWkQxXk3euiC2Ecnt1m9qvgSSlE2zJl2PbLLv20zbwJ4xLDSDXToNy6a1PYkmOL5jubjC88TY9kt4gCYRP8+wgC/ZYpow9FnSob1Ch7Gg/sSBhTJPNHlyfSG1+DcrtntIKloBfwTmyRlhKJ5XETt3l1pyfgCh+8CiLXOjZEJ0TbUKaddsydgDYqJl837HsbHTGxkAs61NbO1BPlfP0+uJGO3KQngs2hAWZ5xyHh7rbwBw/Pw1ghiXYepBLQLuQckGbyNlTf1Wv2kuEj0/JprxPE5wVAkvlFSHvHYqRPs0dL4jWpRji00gBis38ZEjVhntUjfFr9rceK4la1pzjawCxaC1QCiclvTMtHxKmcygbOJZkl4J7Ocl/90aWvNlsL82PYBN4DB4XNkH6S7L29Ccjqar4Dkd+VaUW7R2Immgq9CpFmWFpNyQsScMShG4Xb/xeuJ7Do5Bs4cUo9PgpWZAHVovWvu0ZgUfit0TJMoBF2EmtEJiRtDmvaArMxJTs3bu/gGiRHBh1Z+KvZ7vpjLS+eKfh9m4jux59VBdbNCd3BV5nFWkLQRPCNxnCLWC/Fgb0TprBmVwrXOUOE29lWSLcFOsaJ620h/O5cZJd5vajBT1aU3Ok8ooYXuoUni9TqviMiPP9Mj4oURrm2+oJM=
  - secure: QJn8Tnnixt+w2dDYfTbB7QyR5Soo8j/jWClZSj2ZPEnc52II+xIiXBRoNwGkzt4oAhTwucg8Qg53/hJ1dt8zhLxQ6psJNkW/H3jw8HeRTww2UYOLS8GlpRe63k+LJUS4eGpqkcHIhQe0JatvMM4fNA3h81Zk8jzIMWUs0aq13AiPWOg7y8jd6VbJaojKXg4an5SRu2j0Q52XmwIQUQz1j6sYOPpbBPpHElLek4wx62xA2Tkh+fFNN+m+wXU9idcSJ941075nKCd6gj0cNFWLNMAFAE8XofTThKieU0Hzl9rHbdmy9hVR2gIHVq/FJyvGi7ZrmA+Qs1oZbnl/SuYFgI8CZKM9P0sBEwpO+MXp7okJNSUHDiRd6VCpeW5IVn8cYXoPPGynKLumBRQDj/r1ptu6sVP7KWSefMN0E2nkJV/72GBhar6He0p2YydYSH7+9jmG+CbUFTP5NP8c3jeU/eJp3ORuXp+2fEuz3jHonLE+AFYmaxB+9z7l+GkgMWcTEYZXlGWT/fV5eaxntY5QvqWg5YduE5trQeaJmMBkv1zSI80RkdCwYIfdkFcoqzycB7lp/wZsrWp16qIF3SRTpiN6tDfLgvgNaYwQV32ByMXTJTEImFurA2zNdeUj/LR207eN+vEpZrtHxqwBT7KdnUErAfy4robrUQ32auel5Ys=
after_success: "$COPY_CMD"
