language: java
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: BYvTrd+hv8hH//sTzKytlFPSk+KlGIG5jchMVCczDLL/+Zpfj0kmQ4EtRTa3fhKzFNik5yy+xean4E1GltruFixLXlXVR6FjZXwlxI7SsKkL+nzfGu20PB8NZwK/ETDQmAgaBD6GH6AGg+CQ7g41kVlJ4YFUYGoEXlPlj27gAdD1yzNyOIulCu1loVAaxhupj+kQQdE9ZTUWSjaHTBIPk0CcXEt3A1uYlrKCa8Gqpc/uKtoVbDhX9W3p0Q+Bu+6U/oRqe0X39FNvmvhKbHjMOTnLEln4RtOhC4pn9ojx/TDgTEI9TM+6zEi4JN11ao2Va3/rwl/fM+8tOtvD5p074r2mYXMm5Pt+uNkAaPJ0Ms7VHQ1ST3Qr+ST2ubnDwRgPAqvgLmnkbfuGm49dvC/QhrE+h8wOuw3/TNNnP9VFTtU7XbIKwQ82XiIIivMnjMhvAFGVf8bq4umdVxXYBVahHZ9Zcgmc3YYnrn048BXWq2t8kDTCbRp3vBaG7FR+Hh/+lb+/VA4CUS9K3NNzDNVFs8+HXbvHGMRo1zEfFPdH301d83pQyjfzm9SS5anwDwxCDBGXzRhGytY7OhqE56gTip819IC+yDRO+dBJ+bE2WuH0uwlL+mSd5a2aRhVsQq92R2D5rEWj/NaZ6lKnpISOE/18xRSG2NN98Tu0iMrg210=
after_success: scp target/lab-bot-0.0.1-SNAPSHOT.jar $ALL_IP
