language: java
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: mvn install
jdk:
- oraclejdk8
env:
  matrix:
  - secure: GEyNzSc4HaYn+cLj3viROWDBF9FmuFbqMRiWy/VkrTpOIRLalGg06in9etMjHBXnJE7Sq4J2NztsIiLgpTNrM4BqM4kuHYOa/w+RtYtubD5Um90od2K5qKaBjhYovA1E2doImNhvfEeJ9zCJMZsHbj9vZSEI8taKt+rNIrrOfFnl2KQV99Jj6FkpBbAvrdLqJ3JYQ93r7+i35z9XYGwNw7TgdgX3XJrgvIp//B1ozxYfRhaABmMFEld10C+ZFZldRPM7HdtCaUAbHLk8SOXFbwi8r6scnCI/xFNeNJycwO4lelrLVYx9CXRHVlP4ymy+Nchs/YMsuZq5fjKeiRhE3KRAB10g7LoqjPZzRlCzMK7UKjcvKs9smdkPgCMfHKZ3epKF1B4hRTjrK6AmzZleZRA46jEzj11evkSNopauRQM/8JHLXrh1jRSTOGHnWxHfRFnGQ4l0vbiYkil4lSUZmgoHBe/6KoEFdaJ6sS67eQats95tyKn2n1bwBYoxYySWKJlUaBvoCvLgUbhzDPmQdfFoYZc6j3+7UNlGx2LLi2d90RJ23Ed8HPNuyZfV2HHoiIyOEweYayyEAN0sjb3xdhQQFX8Cbm20h29pnxUsywFKsTxEdsIMjSc0Py5nZHaHHcUnI79yh0WHYlo8liw/ybeIxVoDFmqGyJhR4ngVahM=
after_success: scp [-P 22] target/lab-bot-0.0.1-SNAPSHOT.jar $ALL_IP
